server:
  port: 8081

spring:
  main:
    banner-mode: console ##(console, log, off)

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_DOMAIN}
          audience: ${AUTH0_AUDIENCE}
  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update  ##(create, create-drop, validate, update)
    show-sql: false
    properties:
      hibernate:
        dialect: oracle.jdbc.OracleDriver #(org.hibernate.dialect.OracleSqlAstDialect, org.hibernate.dialect.OracleDialect, org.hibernate.dialect.Oracle12Dialect, org.hibernate.dialect.Oracle12cDialect)
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        
logging:
  level:
    org.springframework.security: DEBUG
